apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  namespace: test
data:
  vmagent.yml: |
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: 'blackbox_exporter_status'
        metrics_path: /probe
        scrape_interval: 30s
        scrape_timeout: 10s
        params:
          module: ["http_2xx"]
        static_configs:
          - targets: ["https://www.google.com"]
